### PR TITLE
modified navbar fixes #26

### LINKED ISSUE #26: navbar modification
image
<br>
navbar doesn't close after clicking the hamburger icon again   <br>
I'm thinking of creating such navbar (one in images below)   <br>
image
mobile/tab view : image

### PR DESCRIPTION
**Pull request by Saurav-Singh-Rauthan**

### CODE REVIEW

**Comment by Saurav-Singh-Rauthan** [comment]
@MitAbhay have a look

**Review by MitAbhay — COMMENTED** [review]
- The navbar width is too much.
- Look at the services page, the navbar is making it odd.
- The color combination is also not good (white on hovering).

**Comment by Saurav-Singh-Rauthan** [comment]
Is this problem on desktop view or mobile view
What is the desired width and colour combination

**Comment by MitAbhay** [comment]
> Is this problem on desktop view or mobile view What is the desired width and colour combination

this is on desktop, make the width as previous and color combination according to the other colors on the website.

**Comment by Saurav-Singh-Rauthan** [comment]
@MitAbhay done

**Review by MitAbhay — APPROVED** [review]

**Pull request merged**
